sonar.projectKey=medibook-frontend
sonar.projectName=MediBook Frontend
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=\
  **/node_modules/**,\
  **/*.spec.ts,\
  **/environments/**,\
  **/*.module.ts,\
  dist/**,\
  coverage/**

sonar.typescript.tsconfigPaths=tsconfig.json,tsconfig.spec.json

sonar.javascript.lcov.reportPaths=coverage/medibook/lcov.info

sonar.sourceEncoding=UTF-8